### ISSUE TITLE
Cannot load images - image file format "png" not supported 

### ISSUE THREAD

**Issue by PlanetRenox** [Raimondi/scid#1]
Successfully installed Scid on Debian, now when I try to launch by "sudo ./scid" I'm getting an error 'Cannot load images - image file format "png" not supported.'

What I tried: I tried installing libtk-img as the other thread mentioned but i'm still getting the same error.

Please let me know how i can get around this.

**Comment by Raimondi** [comment]
This is not an official repo of the project, check [here](https://sourceforge.net/p/scid/wiki/ContactUs/) for an option to contact the maintainers.
